FROM python:3.7-alpine

RUN mkdir /minitwit

COPY minitwit_mysql.py /minitwit/
COPY requirements.txt /minitwit/
COPY static /minitwit/static
COPY templates /minitwit/templates

WORKDIR /minitwit

RUN pip install -r requirements.txt

EXPOSE 5000

ENTRYPOINT ["python", "minitwit_mysql.py"]
